### ISSUE TITLE
JG: Consider reordering the article

### ISSUE THREAD

**Issue by hturner** [Abhi-1U/texor-rjarticle#4]
Comment from @ajrgodfrey:

> Consider reordering the main article:
> 
> 1.  Why and how to do it the right way (what does good look like) try to convince readers to do it via R Markdown first, so that conversion is not necessary in future.  
> 2.  How to convert legacy articles.

This might be a bit much to do at this stage.

**Comment by dicook** [comment]
Thanks @ajrgodfrey. We are separately writing an article on the rjtools package, and this is best put into that paper. I'm adding an issue to that repo.
